// The chore catalog behind quick-add's suggestion list (ADR 0014).
//
// Static data, identical for every household, ~200 entries — small enough to
// ship in the bundle (~4 kB gzipped) and match in the browser, which is why
// there is no table, no endpoint and no index to keep warm.
//
// Shape:
//   id        stable slug; never reused, never renamed (tests key off it)
//   name      the exact text that lands in the name field, in Polish
//   category  a default key from CATEGORIES — falls back to 'home' when the
//             household has deleted that category (they are editable, ADR 0013)
//   interval  a suggested rhythm WITHOUT `startsOn`. The anchor is stamped from
//             today when the suggestion is picked, because an interval's
//             meaning depends on its anchor (ADR 0010) and a canned anchor
//             would be a lie. RhythmEditor still shows both for confirmation.
//   keywords  folded-and-tokenised aliases. This is where Polish morphology is
//             handled: the forms people actually type ("podlewanie", "podlac"),
//             not a full paradigm. 2–4 is usually enough; see choreSearch.js.
//
// The suggested rhythms are opinions, not facts, and every one of them is
// editable in the sheet before the task is saved. Where a real-world interval
// varies a lot (filters, servicing), the entry leans towards the longer end —
// a chore nagging too early trains people to ignore the list.
//
// Invariants are enforced by choreCatalog.test.js, not by convention.

export const CHORE_CATALOG = [
  // ── Rośliny ───────────────────────────────────────────────────────────────
  {
    id: 'water-indoor-plants',
    name: 'Podlać kwiaty w domu',
    category: 'plants',
    interval: { type: 'everyNDays', n: 3 },
    keywords: ['podlewanie', 'podlac', 'kwiatki', 'doniczki', 'woda'],
  },
  {
    id: 'water-balcony',
    name: 'Podlać balkon',
    category: 'plants',
    interval: { type: 'everyNDays', n: 2 },
    keywords: ['podlewanie', 'taras', 'skrzynki', 'pelargonie'],
  },
  {
    id: 'water-garden',
    name: 'Podlać ogród',
    category: 'plants',
    interval: { type: 'everyNDays', n: 3 },
    keywords: ['podlewanie', 'grządki', 'warzywnik', 'wąż'],
  },
  {
    id: 'water-monstera',
    name: 'Podlać monsterę',
    category: 'plants',
    interval: { type: 'everyNDays', n: 7 },
    keywords: ['monstera', 'podlewanie'],
  },
  {
    id: 'water-succulents',
    name: 'Podlać sukulenty',
    category: 'plants',
    interval: { type: 'everyNDays', n: 14 },
    keywords: ['sukulenty', 'kaktusy', 'podlewanie'],
  },
  {
    id: 'water-orchids',
    name: 'Podlać storczyki',
    category: 'plants',
    interval: { type: 'everyNDays', n: 7 },
    keywords: ['storczyk', 'orchidea', 'podlewanie', 'zanurzanie'],
  },
  {
    id: 'water-herbs',
    name: 'Podlać zioła w kuchni',
    category: 'plants',
    interval: { type: 'everyNDays', n: 2 },
    keywords: ['zioła', 'bazylia', 'mięta', 'podlewanie'],
  },
  {
    id: 'fertilise-plants',
    name: 'Nawieźć kwiaty',
    category: 'plants',
    interval: { type: 'everyNDays', n: 14 },
    keywords: ['nawóz', 'nawożenie', 'odżywka', 'nawiezc'],
  },
  {
    id: 'mist-plants',
    name: 'Zrosić liście',
    category: 'plants',
    interval: { type: 'everyNDays', n: 4 },
    keywords: ['zraszanie', 'rosic', 'spryskać', 'wilgotność'],
  },
  {
    id: 'wipe-leaves',
    name: 'Przetrzeć liście z kurzu',
    category: 'plants',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['liście', 'kurz', 'przecieranie'],
  },
  {
    id: 'repot-plants',
    name: 'Przesadzić rośliny',
    category: 'plants',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['przesadzanie', 'doniczka', 'ziemia', 'przesadzic'],
  },
  {
    id: 'rotate-plants',
    name: 'Obrócić doniczki do światła',
    category: 'plants',
    interval: { type: 'weekly', weekdays: [7] },
    keywords: ['obracanie', 'doniczki', 'światło'],
  },
  {
    id: 'deadhead-plants',
    name: 'Usunąć suche liście i kwiaty',
    category: 'plants',
    interval: { type: 'weekly', weekdays: [6] },
    keywords: ['przycinanie', 'suche', 'liście', 'usunac'],
  },
  {
    id: 'check-plant-pests',
    name: 'Sprawdzić rośliny pod kątem szkodników',
    category: 'plants',
    interval: { type: 'everyNDays', n: 21 },
    keywords: ['przędziorki', 'mszyce', 'szkodniki', 'sprawdzic'],
  },
  {
    id: 'mow-lawn',
    name: 'Skosić trawnik',
    category: 'plants',
    interval: { type: 'everyNDays', n: 10 },
    keywords: ['koszenie', 'trawa', 'kosiarka', 'skosic'],
  },
  {
    id: 'trim-hedge',
    name: 'Przyciąć żywopłot',
    category: 'plants',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['żywopłot', 'przycinanie', 'nożyce'],
  },
  {
    id: 'weed-beds',
    name: 'Wypielić grządki',
    category: 'plants',
    interval: { type: 'everyNDays', n: 14 },
    keywords: ['pielenie', 'chwasty', 'grządki', 'wypielic'],
  },
  {
    id: 'rake-leaves',
    name: 'Zgrabić liście',
    category: 'plants',
    interval: { type: 'weekly', weekdays: [6] },
    keywords: ['grabienie', 'liście', 'grabie'],
  },
  {
    id: 'compost',
    name: 'Wynieść do kompostownika',
    category: 'plants',
    interval: { type: 'weekly', weekdays: [7] },
    keywords: ['kompost', 'kompostownik', 'bio'],
  },
  {
    id: 'water-christmas-tree',
    name: 'Dolać wody do choinki',
    category: 'plants',
    interval: { type: 'daily' },
    keywords: ['choinka', 'podlewanie', 'święta'],
  },
  {
    id: 'feed-lawn',
    name: 'Nawieźć trawnik',
    category: 'plants',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['nawóz', 'trawnik', 'nawożenie'],
  },
  {
    id: 'clean-pots',
    name: 'Umyć podstawki pod doniczkami',
    category: 'plants',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['podstawki', 'doniczki', 'mycie', 'umyc'],
  },
  {
    id: 'harvest-herbs',
    name: 'Zebrać zioła',
    category: 'plants',
    interval: { type: 'weekly', weekdays: [7] },
    keywords: ['zbiór', 'zioła', 'zebrac'],
  },
  {
    id: 'sweep-terrace',
    name: 'Zamieść taras',
    category: 'plants',
    interval: { type: 'weekly', weekdays: [6] },
    keywords: ['taras', 'zamiatanie', 'balkon', 'miotła'],
  },
  {
    id: 'winterise-garden',
    name: 'Zabezpieczyć rośliny na zimę',
    category: 'plants',
    interval: { type: 'monthly', unit: 'year', every: 1 },
    keywords: ['zima', 'okrycie', 'agrowłóknina', 'zabezpieczyc'],
  },
  {
    id: 'clean-bird-feeder',
    name: 'Uzupełnić karmnik',
    category: 'plants',
    interval: { type: 'weekly', weekdays: [6] },
    keywords: ['karmnik', 'ptaki', 'ziarno', 'uzupelnic'],
  },
  {
    id: 'change-flower-water',
    name: 'Wymienić wodę w wazonie',
    category: 'plants',
    interval: { type: 'everyNDays', n: 2 },
    keywords: ['wazon', 'kwiaty', 'woda', 'wymiana'],
  },
  {
    id: 'aquarium-water',
    name: 'Wymienić wodę w akwarium',
    category: 'plants',
    interval: { type: 'everyNDays', n: 14 },
    keywords: ['akwarium', 'ryby', 'woda', 'podmiana'],
  },
  {
    id: 'garden-tools',
    name: 'Naostrzyć i naoliwić narzędzia ogrodowe',
    category: 'plants',
    interval: { type: 'monthly', day: 'last' },
    keywords: ['sekator', 'narzędzia', 'ostrzenie', 'naostrzyc'],
  },
  {
    id: 'seedlings',
    name: 'Doglądać rozsady',
    category: 'plants',
    interval: { type: 'everyNDays', n: 2 },
    keywords: ['rozsada', 'siewki', 'sadzonki'],
  },

  // ── Sprzęt ────────────────────────────────────────────────────────────────
  {
    id: 'kitchen-hood-filter',
    name: 'Umyć filtr okapu',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['okap', 'filtr', 'kuchnia', 'tłuszcz'],
  },
  {
    id: 'hood-carbon-filter',
    name: 'Wymienić filtr węglowy w okapie',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['okap', 'filtr', 'węglowy', 'wymiana'],
  },
  {
    id: 'water-filter-jug',
    name: 'Wymienić wkład w dzbanku filtrującym',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['filtr', 'wkład', 'dzbanek', 'woda', 'brita'],
  },
  {
    id: 'water-filter-tap',
    name: 'Wymienić filtr wody pod zlewem',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['filtr', 'woda', 'zlew', 'osmoza'],
  },
  {
    id: 'vacuum-filter',
    name: 'Umyć filtr odkurzacza',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['odkurzacz', 'filtr', 'hepa', 'mycie'],
  },
  {
    id: 'vacuum-bag',
    name: 'Wymienić worek w odkurzaczu',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['odkurzacz', 'worek', 'wymiana'],
  },
  {
    id: 'robot-vacuum-brush',
    name: 'Wyczyścić szczotki robota sprzątającego',
    category: 'equipment',
    interval: { type: 'weekly', weekdays: [7] },
    keywords: ['robot', 'odkurzacz', 'szczotka', 'włosy'],
  },
  {
    id: 'washing-machine-clean',
    name: 'Przepuścić pralkę na pusto',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['pralka', 'czyszczenie', 'kamień', 'pusty'],
  },
  {
    id: 'washing-machine-filter',
    name: 'Wyczyścić filtr pralki',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['pralka', 'filtr', 'pompa'],
  },
  {
    id: 'washing-machine-gasket',
    name: 'Przetrzeć uszczelkę pralki',
    category: 'equipment',
    interval: { type: 'weekly', weekdays: [7] },
    keywords: ['pralka', 'uszczelka', 'pleśń', 'guma'],
  },
  {
    id: 'dryer-lint',
    name: 'Wyczyścić filtr suszarki',
    category: 'equipment',
    interval: { type: 'weekly', weekdays: [7] },
    keywords: ['suszarka', 'filtr', 'kłaczki'],
  },
  {
    id: 'dishwasher-filter',
    name: 'Wyczyścić filtr zmywarki',
    category: 'equipment',
    interval: { type: 'weekly', weekdays: [7] },
    keywords: ['zmywarka', 'filtr', 'sitko'],
  },
  {
    id: 'dishwasher-salt',
    name: 'Uzupełnić sól i nabłyszczacz w zmywarce',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['zmywarka', 'sól', 'nabłyszczacz', 'uzupelnic'],
  },
  {
    id: 'dishwasher-clean',
    name: 'Przepuścić zmywarkę na pusto',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['zmywarka', 'czyszczenie', 'pusty'],
  },
  {
    id: 'fridge-clean',
    name: 'Umyć lodówkę',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['lodówka', 'mycie', 'półki', 'umyc'],
  },
  {
    id: 'fridge-throw-out',
    name: 'Przejrzeć lodówkę i wyrzucić przeterminowane',
    category: 'equipment',
    interval: { type: 'weekly', weekdays: [7] },
    keywords: ['lodówka', 'przeterminowane', 'przegląd', 'jedzenie'],
  },
  {
    id: 'freezer-defrost',
    name: 'Rozmrozić zamrażarkę',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['zamrażarka', 'rozmrażanie', 'szron'],
  },
  {
    id: 'oven-clean',
    name: 'Wyczyścić piekarnik',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['piekarnik', 'czyszczenie', 'piroliza', 'tłuszcz'],
  },
  {
    id: 'microwave-clean',
    name: 'Umyć mikrofalówkę',
    category: 'equipment',
    interval: { type: 'weekly', weekdays: [7] },
    keywords: ['mikrofalówka', 'mycie', 'kuchenka'],
  },
  {
    id: 'kettle-descale',
    name: 'Odkamienić czajnik',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['czajnik', 'kamień', 'ocet', 'odkamienianie'],
  },
  {
    id: 'coffee-descale',
    name: 'Odkamienić ekspres do kawy',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['ekspres', 'kawa', 'kamień', 'odkamienianie'],
  },
  {
    id: 'coffee-clean-group',
    name: 'Wyczyścić zaparzacz ekspresu',
    category: 'equipment',
    interval: { type: 'weekly', weekdays: [7] },
    keywords: ['ekspres', 'zaparzacz', 'kawa', 'tabletka'],
  },
  {
    id: 'air-purifier-filter',
    name: 'Wymienić filtr oczyszczacza powietrza',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['oczyszczacz', 'filtr', 'powietrze', 'smog'],
  },
  {
    id: 'humidifier-clean',
    name: 'Umyć nawilżacz',
    category: 'equipment',
    interval: { type: 'weekly', weekdays: [7] },
    keywords: ['nawilżacz', 'mycie', 'kamień'],
  },
  {
    id: 'ac-filter',
    name: 'Umyć filtry klimatyzacji',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['klimatyzacja', 'filtr', 'klima'],
  },
  {
    id: 'ventilation-grilles',
    name: 'Odkurzyć kratki wentylacyjne',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['wentylacja', 'kratki', 'odkurzanie'],
  },
  {
    id: 'recuperator-filter',
    name: 'Wymienić filtry rekuperatora',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['rekuperator', 'filtr', 'wentylacja'],
  },
  {
    id: 'boiler-service',
    name: 'Przegląd pieca',
    category: 'equipment',
    interval: { type: 'monthly', unit: 'year', every: 1 },
    keywords: ['piec', 'kocioł', 'przegląd', 'serwis'],
  },
  {
    id: 'chimney-sweep',
    name: 'Kominiarz',
    category: 'equipment',
    interval: { type: 'monthly', unit: 'year', every: 1 },
    keywords: ['kominiarz', 'komin', 'przegląd'],
  },
  {
    id: 'radiator-bleed',
    name: 'Odpowietrzyć kaloryfery',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['kaloryfer', 'grzejnik', 'odpowietrzanie'],
  },
  {
    id: 'water-heater-check',
    name: 'Sprawdzić ciśnienie w instalacji',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['ciśnienie', 'manometr', 'instalacja', 'sprawdzic'],
  },
  {
    id: 'smoke-detector',
    name: 'Sprawdzić czujnik dymu',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['czujnik', 'dym', 'bateria', 'alarm'],
  },
  {
    id: 'co-detector',
    name: 'Sprawdzić czujnik czadu',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['czad', 'czujnik', 'tlenek', 'bateria'],
  },
  {
    id: 'car-tyre-pressure',
    name: 'Sprawdzić ciśnienie w oponach',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['opony', 'ciśnienie', 'auto', 'samochód'],
  },
  {
    id: 'car-oil',
    name: 'Sprawdzić poziom oleju w aucie',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['olej', 'auto', 'samochód', 'bagnet'],
  },
  {
    id: 'car-service',
    name: 'Przegląd auta',
    category: 'equipment',
    interval: { type: 'monthly', unit: 'year', every: 1 },
    keywords: ['auto', 'samochód', 'przegląd', 'serwis'],
  },
  {
    id: 'car-wash',
    name: 'Umyć auto',
    category: 'equipment',
    interval: { type: 'everyNDays', n: 21 },
    keywords: ['auto', 'samochód', 'myjnia', 'mycie'],
  },
  {
    id: 'car-vacuum',
    name: 'Odkurzyć auto',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['auto', 'samochód', 'odkurzanie', 'wnętrze'],
  },
  {
    id: 'car-washer-fluid',
    name: 'Dolać płyn do spryskiwaczy',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['spryskiwacze', 'płyn', 'auto', 'zima'],
  },
  {
    id: 'car-tyre-swap',
    name: 'Wymienić opony',
    category: 'equipment',
    interval: { type: 'monthly', unit: 'month', every: 6, day: 'first' },
    keywords: ['opony', 'zimowe', 'letnie', 'wulkanizacja'],
  },
  {
    id: 'car-insurance',
    name: 'Odnowić OC',
    category: 'equipment',
    interval: { type: 'monthly', unit: 'year', every: 1 },
    keywords: ['oc', 'ubezpieczenie', 'auto', 'polisa'],
  },
  {
    id: 'bike-service',
    name: 'Naoliwić łańcuch w rowerze',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['rower', 'łańcuch', 'olej', 'smarowanie'],
  },
  {
    id: 'bike-tyres',
    name: 'Napompować rower',
    category: 'equipment',
    interval: { type: 'everyNDays', n: 21 },
    keywords: ['rower', 'opony', 'pompka', 'napompowac'],
  },
  {
    id: 'battery-swap',
    name: 'Wymienić baterie w pilotach',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['baterie', 'pilot', 'wymiana'],
  },
  {
    id: 'printer-ink',
    name: 'Sprawdzić tusz w drukarce',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['drukarka', 'tusz', 'toner'],
  },
  {
    id: 'backup-photos',
    name: 'Zrobić kopię zdjęć',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['backup', 'kopia', 'zdjęcia', 'dysk'],
  },
  {
    id: 'router-restart',
    name: 'Zrestartować router',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['router', 'internet', 'restart', 'wifi'],
  },
  {
    id: 'update-devices',
    name: 'Zaktualizować sprzęt w domu',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['aktualizacja', 'update', 'oprogramowanie'],
  },
  {
    id: 'knife-sharpen',
    name: 'Naostrzyć noże',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['noże', 'ostrzenie', 'kuchnia', 'naostrzyc'],
  },
  {
    id: 'grill-clean',
    name: 'Wyczyścić grilla',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['grill', 'ruszt', 'czyszczenie'],
  },
  {
    id: 'iron-descale',
    name: 'Odkamienić żelazko',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['żelazko', 'kamień', 'para'],
  },
  {
    id: 'sewing-machine-oil',
    name: 'Naoliwić maszynę do szycia',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['maszyna', 'szycie', 'olej'],
  },
  {
    id: 'toolbox-check',
    name: 'Uzupełnić skrzynkę z narzędziami',
    category: 'equipment',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['narzędzia', 'skrzynka', 'śruby'],
  },

  // ── Dom ───────────────────────────────────────────────────────────────────
  {
    id: 'take-out-rubbish',
    name: 'Wynieść śmieci',
    category: 'home',
    interval: { type: 'everyNDays', n: 2 },
    keywords: ['śmieci', 'kosz', 'wyniesc', 'odpady'],
  },
  {
    id: 'take-out-recycling',
    name: 'Wynieść segregację',
    category: 'home',
    interval: { type: 'weekly', weekdays: [2] },
    keywords: ['segregacja', 'plastik', 'szkło', 'papier', 'recykling'],
  },
  {
    id: 'take-out-glass',
    name: 'Wynieść szkło',
    category: 'home',
    interval: { type: 'weekly', weekdays: [6] },
    keywords: ['szkło', 'butelki', 'segregacja'],
  },
  {
    id: 'bins-out',
    name: 'Wystawić kubły przed dom',
    category: 'home',
    interval: { type: 'weekly', weekdays: [1] },
    keywords: ['kubły', 'śmieci', 'wywóz', 'wystawic'],
  },
  {
    id: 'wash-dishes',
    name: 'Pozmywać',
    category: 'home',
    interval: { type: 'daily' },
    keywords: ['zmywanie', 'naczynia', 'pozmywac'],
  },
  {
    id: 'empty-dishwasher',
    name: 'Wyładować zmywarkę',
    category: 'home',
    interval: { type: 'daily' },
    keywords: ['zmywarka', 'naczynia', 'wyladowac'],
  },
  {
    id: 'wipe-counters',
    name: 'Przetrzeć blaty w kuchni',
    category: 'home',
    interval: { type: 'daily' },
    keywords: ['blat', 'kuchnia', 'przetarcie'],
  },
  {
    id: 'clean-hob',
    name: 'Umyć płytę kuchenną',
    category: 'home',
    interval: { type: 'everyNDays', n: 2 },
    keywords: ['płyta', 'kuchenka', 'indukcja', 'mycie'],
  },
  {
    id: 'clean-sink',
    name: 'Wyszorować zlew',
    category: 'home',
    interval: { type: 'weekly', weekdays: [7] },
    keywords: ['zlew', 'szorowanie', 'kuchnia'],
  },
  {
    id: 'drain-unclog',
    name: 'Przepłukać odpływy',
    category: 'home',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['odpływ', 'syfon', 'kret', 'zatkany'],
  },
  {
    id: 'kitchen-cloths',
    name: 'Wymienić ścierki kuchenne',
    category: 'home',
    interval: { type: 'everyNDays', n: 3 },
    keywords: ['ścierki', 'kuchnia', 'wymiana'],
  },
  {
    id: 'sponge-swap',
    name: 'Wymienić gąbkę do naczyń',
    category: 'home',
    interval: { type: 'weekly', weekdays: [7] },
    keywords: ['gąbka', 'zmywak', 'wymiana'],
  },
  {
    id: 'vacuum-flat',
    name: 'Odkurzyć mieszkanie',
    category: 'home',
    interval: { type: 'weekly', weekdays: [6] },
    keywords: ['odkurzanie', 'odkurzacz', 'podłogi'],
  },
  {
    id: 'mop-floors',
    name: 'Umyć podłogi',
    category: 'home',
    interval: { type: 'weekly', weekdays: [6] },
    keywords: ['mop', 'podłogi', 'mycie', 'umyc'],
  },
  {
    id: 'dust-surfaces',
    name: 'Zetrzeć kurze',
    category: 'home',
    interval: { type: 'weekly', weekdays: [6] },
    keywords: ['kurz', 'ścieranie', 'półki', 'zetrzec'],
  },
  {
    id: 'clean-mirrors',
    name: 'Umyć lustra',
    category: 'home',
    interval: { type: 'weekly', weekdays: [6] },
    keywords: ['lustro', 'mycie', 'łazienka'],
  },
  {
    id: 'clean-windows',
    name: 'Umyć okna',
    category: 'home',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['okna', 'szyby', 'mycie'],
  },
  {
    id: 'wash-curtains',
    name: 'Wyprać firany',
    category: 'home',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['firany', 'zasłony', 'pranie'],
  },
  {
    id: 'change-bedding',
    name: 'Zmienić pościel',
    category: 'home',
    interval: { type: 'everyNDays', n: 14 },
    keywords: ['pościel', 'łóżko', 'zmiana', 'prześcieradło'],
  },
  {
    id: 'flip-mattress',
    name: 'Obrócić materac',
    category: 'home',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['materac', 'obracanie', 'łóżko'],
  },
  {
    id: 'air-duvets',
    name: 'Wywietrzyć kołdry',
    category: 'home',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['kołdra', 'wietrzenie', 'poduszki'],
  },
  {
    id: 'laundry-wash',
    name: 'Wstawić pranie',
    category: 'home',
    interval: { type: 'everyNDays', n: 3 },
    keywords: ['pranie', 'pralka', 'wstawic'],
  },
  {
    id: 'laundry-hang',
    name: 'Rozwiesić pranie',
    category: 'home',
    interval: { type: 'everyNDays', n: 3 },
    keywords: ['pranie', 'suszarka', 'rozwiesic'],
  },
  {
    id: 'laundry-fold',
    name: 'Poskładać pranie',
    category: 'home',
    interval: { type: 'everyNDays', n: 3 },
    keywords: ['pranie', 'składanie', 'szafa'],
  },
  {
    id: 'ironing',
    name: 'Wyprasować',
    category: 'home',
    interval: { type: 'weekly', weekdays: [7] },
    keywords: ['prasowanie', 'żelazko', 'koszule'],
  },
  {
    id: 'wash-towels',
    name: 'Wyprać ręczniki',
    category: 'home',
    interval: { type: 'weekly', weekdays: [7] },
    keywords: ['ręczniki', 'pranie', 'łazienka'],
  },
  {
    id: 'clean-toilet',
    name: 'Umyć toaletę',
    category: 'home',
    interval: { type: 'everyNDays', n: 4 },
    keywords: ['toaleta', 'wc', 'muszla', 'mycie'],
  },
  {
    id: 'clean-bathroom',
    name: 'Wysprzątać łazienkę',
    category: 'home',
    interval: { type: 'weekly', weekdays: [6] },
    keywords: ['łazienka', 'sprzątanie', 'kabina'],
  },
  {
    id: 'clean-shower',
    name: 'Umyć kabinę prysznicową',
    category: 'home',
    interval: { type: 'weekly', weekdays: [6] },
    keywords: ['prysznic', 'kabina', 'kamień', 'mycie'],
  },
  {
    id: 'shower-curtain',
    name: 'Wyprać zasłonkę prysznicową',
    category: 'home',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['zasłonka', 'prysznic', 'pleśń'],
  },
  {
    id: 'descale-taps',
    name: 'Odkamienić baterie i słuchawkę',
    category: 'home',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['kamień', 'bateria', 'kran', 'słuchawka'],
  },
  {
    id: 'bathroom-mats',
    name: 'Wyprać dywaniki łazienkowe',
    category: 'home',
    interval: { type: 'everyNDays', n: 14 },
    keywords: ['dywanik', 'łazienka', 'pranie'],
  },
  {
    id: 'toothbrush-head',
    name: 'Wymienić główkę szczoteczki',
    category: 'home',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['szczoteczka', 'główka', 'zęby', 'wymiana'],
  },
  {
    id: 'restock-toiletries',
    name: 'Uzupełnić papier i mydło',
    category: 'home',
    interval: { type: 'weekly', weekdays: [7] },
    keywords: ['papier', 'mydło', 'zapas', 'uzupelnic'],
  },
  {
    id: 'grocery-shopping',
    name: 'Zrobić duże zakupy',
    category: 'home',
    interval: { type: 'weekly', weekdays: [6] },
    keywords: ['zakupy', 'sklep', 'spożywcze'],
  },
  {
    id: 'meal-plan',
    name: 'Zaplanować posiłki na tydzień',
    category: 'home',
    interval: { type: 'weekly', weekdays: [7] },
    keywords: ['jadłospis', 'plan', 'posiłki', 'menu'],
  },
  {
    id: 'batch-cook',
    name: 'Ugotować na kilka dni',
    category: 'home',
    interval: { type: 'weekly', weekdays: [7] },
    keywords: ['gotowanie', 'obiad', 'zapas'],
  },
  {
    id: 'pantry-check',
    name: 'Przejrzeć spiżarnię',
    category: 'home',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['spiżarnia', 'zapasy', 'daty', 'przegląd'],
  },
  {
    id: 'tidy-living-room',
    name: 'Ogarnąć salon',
    category: 'home',
    interval: { type: 'daily' },
    keywords: ['salon', 'sprzątanie', 'porządek'],
  },
  {
    id: 'make-beds',
    name: 'Pościelić łóżka',
    category: 'home',
    interval: { type: 'daily' },
    keywords: ['łóżko', 'pościel', 'poranek'],
  },
  {
    id: 'air-rooms',
    name: 'Wywietrzyć mieszkanie',
    category: 'home',
    interval: { type: 'daily' },
    keywords: ['wietrzenie', 'okna', 'powietrze'],
  },
  {
    id: 'check-humidity',
    name: 'Sprawdzić wilgotność w domu',
    category: 'home',
    interval: { type: 'weekly', weekdays: [7] },
    keywords: ['wilgotność', 'higrometr', 'pleśń'],
  },
  {
    id: 'clean-doors',
    name: 'Przetrzeć drzwi i klamki',
    category: 'home',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['drzwi', 'klamki', 'przecieranie'],
  },
  {
    id: 'clean-skirting',
    name: 'Umyć listwy przypodłogowe',
    category: 'home',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['listwy', 'cokoły', 'mycie'],
  },
  {
    id: 'clean-radiators',
    name: 'Odkurzyć za kaloryferami',
    category: 'home',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['kaloryfer', 'grzejnik', 'kurz'],
  },
  {
    id: 'wash-rugs',
    name: 'Wyprać dywan',
    category: 'home',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['dywan', 'pranie', 'chodnik'],
  },
  {
    id: 'clean-upholstery',
    name: 'Odkurzyć kanapę',
    category: 'home',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['kanapa', 'tapicerka', 'odkurzanie'],
  },
  {
    id: 'declutter-wardrobe',
    name: 'Przejrzeć szafę',
    category: 'home',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['szafa', 'ubrania', 'porządki', 'przegląd'],
  },
  {
    id: 'sort-post',
    name: 'Przejrzeć pocztę i papiery',
    category: 'home',
    interval: { type: 'weekly', weekdays: [7] },
    keywords: ['poczta', 'listy', 'papiery', 'dokumenty'],
  },
  {
    id: 'pay-bills',
    name: 'Zapłacić rachunki',
    category: 'home',
    interval: { type: 'monthly', day: 10 },
    keywords: ['rachunki', 'opłaty', 'przelew', 'zaplacic'],
  },
  {
    id: 'pay-rent',
    name: 'Zapłacić czynsz',
    category: 'home',
    interval: { type: 'monthly', day: 10 },
    keywords: ['czynsz', 'spółdzielnia', 'przelew'],
  },
  {
    id: 'meter-reading',
    name: 'Spisać liczniki',
    category: 'home',
    interval: { type: 'monthly', day: 'last' },
    keywords: ['licznik', 'prąd', 'woda', 'gaz', 'odczyt'],
  },
  {
    id: 'budget-review',
    name: 'Przejrzeć wydatki',
    category: 'home',
    interval: { type: 'monthly', day: 'last' },
    keywords: ['budżet', 'wydatki', 'finanse'],
  },
  {
    id: 'subscriptions-review',
    name: 'Przejrzeć subskrypcje',
    category: 'home',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['subskrypcje', 'abonament', 'netflix', 'opłaty'],
  },
  {
    id: 'pet-food',
    name: 'Dokupić karmę',
    category: 'home',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['karma', 'pies', 'kot', 'zwierzę'],
  },
  {
    id: 'litter-box',
    name: 'Wyczyścić kuwetę',
    category: 'home',
    interval: { type: 'everyNDays', n: 2 },
    keywords: ['kuweta', 'kot', 'żwirek'],
  },
  {
    id: 'walk-dog-long',
    name: 'Dłuższy spacer z psem',
    category: 'home',
    interval: { type: 'weekly', weekdays: [6] },
    keywords: ['pies', 'spacer', 'wyjście'],
  },
  {
    id: 'brush-pet',
    name: 'Wyczesać zwierzaka',
    category: 'home',
    interval: { type: 'weekly', weekdays: [7] },
    keywords: ['czesanie', 'sierść', 'pies', 'kot'],
  },
  {
    id: 'pet-vet',
    name: 'Wizyta u weterynarza',
    category: 'home',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['weterynarz', 'szczepienie', 'pies', 'kot'],
  },
  {
    id: 'clean-pet-bowls',
    name: 'Umyć miski zwierzaka',
    category: 'home',
    interval: { type: 'everyNDays', n: 2 },
    keywords: ['miski', 'pies', 'kot', 'mycie'],
  },
  {
    id: 'clean-fridge-magnets',
    name: 'Zaktualizować listę na lodówce',
    category: 'home',
    interval: { type: 'weekly', weekdays: [7] },
    keywords: ['lista', 'lodówka', 'zakupy'],
  },
  {
    id: 'check-mailbox',
    name: 'Sprawdzić skrzynkę pocztową',
    category: 'home',
    interval: { type: 'everyNDays', n: 3 },
    keywords: ['skrzynka', 'poczta', 'listy'],
  },
  {
    id: 'basement-check',
    name: 'Zajrzeć do piwnicy',
    category: 'home',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['piwnica', 'wilgoć', 'przegląd'],
  },
  {
    id: 'garage-tidy',
    name: 'Ogarnąć garaż',
    category: 'home',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['garaż', 'porządki', 'sprzątanie'],
  },
  {
    id: 'wash-bins',
    name: 'Umyć kosz na śmieci',
    category: 'home',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['kosz', 'śmieci', 'mycie'],
  },
  {
    id: 'clean-light-fittings',
    name: 'Umyć lampy i abażury',
    category: 'home',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['lampa', 'żyrandol', 'kurz', 'abażur'],
  },
  {
    id: 'replace-bulbs',
    name: 'Wymienić przepalone żarówki',
    category: 'home',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['żarówka', 'światło', 'wymiana'],
  },
  {
    id: 'clean-switches',
    name: 'Przetrzeć włączniki i kontakty',
    category: 'home',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['włącznik', 'kontakt', 'przecieranie'],
  },
  {
    id: 'wipe-electronics',
    name: 'Przetrzeć telewizor i ekrany',
    category: 'home',
    interval: { type: 'weekly', weekdays: [6] },
    keywords: ['telewizor', 'ekran', 'kurz', 'monitor'],
  },
  {
    id: 'clean-keyboard',
    name: 'Wyczyścić klawiaturę i biurko',
    category: 'home',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['klawiatura', 'biurko', 'okruchy'],
  },
  {
    id: 'check-leaks',
    name: 'Sprawdzić, czy nic nie cieknie',
    category: 'home',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['przeciek', 'rura', 'syfon', 'woda'],
  },
  {
    id: 'clean-washing-powder-drawer',
    name: 'Umyć szufladę na proszek',
    category: 'home',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['szuflada', 'proszek', 'pralka'],
  },
  {
    id: 'stair-sweep',
    name: 'Zamieść klatkę',
    category: 'home',
    interval: { type: 'weekly', weekdays: [6] },
    keywords: ['klatka', 'schody', 'zamiatanie'],
  },
  {
    id: 'snow-clearing',
    name: 'Odśnieżyć wejście',
    category: 'home',
    interval: { type: 'daily' },
    keywords: ['śnieg', 'odśnieżanie', 'chodnik'],
  },
  {
    id: 'doormat-shake',
    name: 'Wytrzepać wycieraczkę',
    category: 'home',
    interval: { type: 'weekly', weekdays: [6] },
    keywords: ['wycieraczka', 'trzepanie', 'przedpokój'],
  },
  {
    id: 'plan-week',
    name: 'Rozpisać tydzień',
    category: 'home',
    interval: { type: 'weekly', weekdays: [7] },
    keywords: ['plan', 'kalendarz', 'tydzień'],
  },
  {
    id: 'call-family',
    name: 'Zadzwonić do rodziców',
    category: 'home',
    interval: { type: 'weekly', weekdays: [7] },
    keywords: ['telefon', 'rodzice', 'babcia', 'zadzwonic'],
  },
  {
    id: 'birthday-check',
    name: 'Sprawdzić nadchodzące urodziny',
    category: 'home',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['urodziny', 'prezent', 'kalendarz'],
  },
  {
    id: 'check-documents',
    name: 'Sprawdzić ważność dokumentów',
    category: 'home',
    interval: { type: 'monthly', unit: 'year', every: 1 },
    keywords: ['dowód', 'paszport', 'prawo jazdy', 'ważność'],
  },
  {
    id: 'donate-clothes',
    name: 'Oddać rzeczy do kontenera',
    category: 'home',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['ubrania', 'oddanie', 'kontener', 'charytatywnie'],
  },
  {
    id: 'e-waste',
    name: 'Oddać elektrośmieci',
    category: 'home',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['elektrośmieci', 'baterie', 'punkt', 'oddac'],
  },

  // ── Zdrowie ───────────────────────────────────────────────────────────────
  {
    id: 'take-vitamin-d',
    name: 'Wziąć witaminę D',
    category: 'health',
    interval: { type: 'daily' },
    keywords: ['witamina', 'suplement', 'wziac'],
  },
  {
    id: 'take-meds',
    name: 'Wziąć leki',
    category: 'health',
    interval: { type: 'daily' },
    keywords: ['leki', 'tabletki', 'lekarstwa'],
  },
  {
    id: 'refill-prescription',
    name: 'Wykupić receptę',
    category: 'health',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['recepta', 'apteka', 'leki'],
  },
  {
    id: 'restock-first-aid',
    name: 'Przejrzeć apteczkę',
    category: 'health',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['apteczka', 'daty', 'leki', 'przegląd'],
  },
  {
    id: 'dentist',
    name: 'Wizyta u dentysty',
    category: 'health',
    interval: { type: 'monthly', unit: 'month', every: 6, day: 'first' },
    keywords: ['dentysta', 'zęby', 'przegląd', 'wizyta'],
  },
  {
    id: 'hygienist',
    name: 'Higienizacja zębów',
    category: 'health',
    interval: { type: 'monthly', unit: 'month', every: 6, day: 'first' },
    keywords: ['higienizacja', 'zęby', 'kamień', 'dentysta'],
  },
  {
    id: 'gp-checkup',
    name: 'Badania okresowe',
    category: 'health',
    interval: { type: 'monthly', unit: 'year', every: 1 },
    keywords: ['badania', 'krew', 'lekarz', 'morfologia'],
  },
  {
    id: 'eye-test',
    name: 'Badanie wzroku',
    category: 'health',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['wzrok', 'okulista', 'okulary'],
  },
  {
    id: 'derma-moles',
    name: 'Sprawdzić znamiona u dermatologa',
    category: 'health',
    interval: { type: 'monthly', unit: 'year', every: 1 },
    keywords: ['znamiona', 'dermatolog', 'pieprzyki'],
  },
  {
    id: 'flu-shot',
    name: 'Szczepienie na grypę',
    category: 'health',
    interval: { type: 'monthly', unit: 'year', every: 1 },
    keywords: ['szczepienie', 'grypa', 'szczepionka'],
  },
  {
    id: 'contact-lenses',
    name: 'Wymienić soczewki',
    category: 'health',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['soczewki', 'kontaktowe', 'wymiana'],
  },
  {
    id: 'workout',
    name: 'Trening',
    category: 'health',
    interval: { type: 'weekly', weekdays: [2, 4, 6] },
    keywords: ['trening', 'siłownia', 'ćwiczenia', 'sport'],
  },
  {
    id: 'walk-10k',
    name: 'Dłuższy spacer',
    category: 'health',
    interval: { type: 'everyNDays', n: 2 },
    keywords: ['spacer', 'kroki', 'ruch'],
  },
  {
    id: 'stretching',
    name: 'Rozciąganie',
    category: 'health',
    interval: { type: 'everyNDays', n: 2 },
    keywords: ['rozciąganie', 'stretching', 'plecy'],
  },
  {
    id: 'back-exercises',
    name: 'Ćwiczenia na kręgosłup',
    category: 'health',
    interval: { type: 'daily' },
    keywords: ['kręgosłup', 'plecy', 'ćwiczenia', 'rehabilitacja'],
  },
  {
    id: 'physio',
    name: 'Wizyta u fizjoterapeuty',
    category: 'health',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['fizjoterapeuta', 'rehabilitacja', 'masaż'],
  },
  {
    id: 'weigh-in',
    name: 'Zważyć się',
    category: 'health',
    interval: { type: 'weekly', weekdays: [1] },
    keywords: ['waga', 'ważenie', 'pomiar'],
  },
  {
    id: 'blood-pressure',
    name: 'Zmierzyć ciśnienie',
    category: 'health',
    interval: { type: 'weekly', weekdays: [1] },
    keywords: ['ciśnienie', 'pomiar', 'ciśnieniomierz'],
  },
  {
    id: 'hair-cut',
    name: 'Fryzjer',
    category: 'health',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['fryzjer', 'włosy', 'strzyżenie'],
  },
  {
    id: 'nails',
    name: 'Obciąć paznokcie',
    category: 'health',
    interval: { type: 'everyNDays', n: 14 },
    keywords: ['paznokcie', 'obcinanie', 'manicure'],
  },
  {
    id: 'floss',
    name: 'Nitkowanie zębów',
    category: 'health',
    interval: { type: 'daily' },
    keywords: ['nitka', 'zęby', 'higiena'],
  },
  {
    id: 'screen-break',
    name: 'Dzień bez ekranu',
    category: 'health',
    interval: { type: 'weekly', weekdays: [7] },
    keywords: ['ekran', 'detoks', 'odpoczynek'],
  },
  {
    id: 'meditate',
    name: 'Medytacja',
    category: 'health',
    interval: { type: 'daily' },
    keywords: ['medytacja', 'oddech', 'spokój'],
  },
  {
    id: 'journal',
    name: 'Zapisać podsumowanie dnia',
    category: 'health',
    interval: { type: 'daily' },
    keywords: ['dziennik', 'notatki', 'podsumowanie'],
  },
  {
    id: 'water-intake',
    name: 'Wypić dzienną normę wody',
    category: 'health',
    interval: { type: 'daily' },
    keywords: ['woda', 'nawodnienie', 'picie'],
  },
  {
    id: 'read-book',
    name: 'Poczytać książkę',
    category: 'health',
    interval: { type: 'daily' },
    keywords: ['książka', 'czytanie', 'wieczór'],
  },
  {
    id: 'sauna',
    name: 'Sauna albo basen',
    category: 'health',
    interval: { type: 'weekly', weekdays: [6] },
    keywords: ['sauna', 'basen', 'pływanie'],
  },
  {
    id: 'sunscreen-check',
    name: 'Sprawdzić datę na kremie z filtrem',
    category: 'health',
    interval: { type: 'monthly', day: 'first' },
    keywords: ['krem', 'filtr', 'spf', 'data'],
  },
  {
    id: 'razor-blade',
    name: 'Wymienić ostrze w maszynce',
    category: 'health',
    interval: { type: 'everyNDays', n: 14 },
    keywords: ['maszynka', 'ostrze', 'golenie', 'żyletka'],
  },
  {
    id: 'clean-glasses',
    name: 'Umyć okulary',
    category: 'health',
    interval: { type: 'everyNDays', n: 3 },
    keywords: ['okulary', 'szkła', 'mycie'],
  },
]
